// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwsipdogkiojxdvrhidn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3c2lwZG9na2lvanhkdnJoaWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NjYyMDUsImV4cCI6MjA2MjI0MjIwNX0.pPDVxUfa2m9S55TDibJwC_xkw3xo0b3ja3B3TpJIhJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);